MA-13527-1 Include libfstab to fix build error
The Android build system disallows dependencies between
vendor modules and vendor unavailable modules after set
the BOARD_VNDK_VERSION as "current".
We put the bootctrl.avb to vendor partition but it depends
on some vendor unavailable modules(libavb_user, libfs_mgr),
build errors will happen like below:
  error: external/avb/Android.bp:220:1: dependency "libavb_user" of
  "bootctrl.avb" missing variant:
      arch:android_arm64_armv8-a_cortex-a53, image:vendor, link:static
  available variants:
      arch:android_arm64_armv8-a_cortex-a53, image:core, link:static
      arch:android_arm_armv7-a-neon_cortex-a9, image:core, link:static
This patch sets the libavb_user as vendor available and use
vendor available module libfstab to replace the libfs_mgr.

Test: bootctrl.avb build pass.

Change-Id: Ia7c178cceaab19e69ac3c0b686c04b4515d48582
Signed-off-by: Luo Ji <ji.luo@nxp.com>